let
    // Build calendar from min/max Sales[OrderDate]
    Sales = Csv.Document(File.Contents("data/sales.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    SalesHeaders = Table.PromoteHeaders(Sales, [PromoteAllScalars=true]),
    Changed = Table.TransformColumnTypes(SalesHeaders,{{"OrderDate", type date}}),
    MinDate = Date.From(List.Min(Changed[OrderDate])),
    MaxDate = Date.From(List.Max(Changed[OrderDate])),
    DayCount = Duration.Days(MaxDate - MinDate) + 1,
    Dates = List.Dates(MinDate, DayCount, #duration(1,0,0,0)),
    Tbl = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
    AddYear = Table.AddColumn(Tbl, "Year", each Date.Year([Date]), Int64.Type),
    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date]), type text),
    AddQuarter = Table.AddColumn(AddMonthName, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
    AddWeek = Table.AddColumn(AddQuarter, "Week", each Date.WeekOfYear([Date]), Int64.Type),
    AddYearMonth = Table.AddColumn(AddWeek, "YearMonth", each Date.ToText([Date], "yyyy-MM"), type text)
in
    AddYearMonth
